# keep this at the top so Compose reads .env in the same folder
version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["${DB_PORT}:5432"]

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # (…rest stays unchanged…)

  auth:
    build: { context: ., args: { SERVICE: "auth" } }
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_MODE: ${SSL_MODE}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${AUTH_PORT}
    depends_on: [db]
    ports: ["${AUTH_PORT}:${AUTH_PORT}"]

  gateway:
    build: { context: ., args: { SERVICE: "gateway" } }
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      PORT: ${GATEWAY_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: [kafka, auth]
    ports: ["${GATEWAY_PORT}:${GATEWAY_PORT}"]

  persist:
    build: { context: ., args: { SERVICE: "persist" } }
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_MODE: ${SSL_MODE}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on: [kafka, db]
